cat keepalived.conf 
global_defs {
router_id WEB02
}

vrrp_script chk_web {
script "/usr/local/bin/check_web.sh"
interval 3
}

vrrp_instance VI_1 {
state BACKUP
interface ens33

virtual_router_id 51

priority 100

authentication {
    auth_type PASS
    auth_pass 1234
}

virtual_ipaddress {
    192.168.11.250
}

track_script {
    chk_web
}

}