#Файл с переменными для удобного конфигурирования zabbix 
---
zabbix_version: "7.0"

zabbix_project_dir: "/opt/zabbix"

zabbix_db_name: "zabbix"
zabbix_db_user: "zabbix"
zabbix_db_password: "{{ zabbix_db_password }}"

zabbix_web_http_port: 80     #Порт веб-интерфейса
zabbix_server_port: 10051    #Порт для активных проверок метрик

zabbix_timezone: "Europe/Moscow"

zabbix_restart_policy: "unless-stopped"