---
- name: Create Elasticsearch directory
  ansible.builtin.file:
    path: /opt/elasticsearch
    state: directory
    mode: "0755"

- name: Copy Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/elasticsearch/docker-compose.yml
    mode: "0644"

- name: Start Elasticsearch
  community.docker.docker_compose_v2:
    project_src: /opt/elasticsearch
    state: present