# Файл с хостами. Данные для подключения по SSH берутся из файла на машине, с которой запускается Ansible: 
#.ssh/config
# Именно в нём реализован proxyjump для подключения 

[webservers]
web-a
web-b

[bastion]
bastion

[elastic]
elastic

[kibana]
kibana

[zabbix]
zabbix

