---
- name: Настройка веб-сервера
  hosts: webservers
  become: true

  roles:
    - nginx
    - zabbix-agent
    - filebeat

- name: Настройка bastion
  hosts: bastion
  become: true

  roles:
    - zabbix-agent
  
- name: Настройка kibana
  hosts: kibana
  become: true

  roles:
    - docker-compose
    - kibana
    - zabbix-agent
    
- name: Настройка elastic
  hosts: elastic
  become: true

  roles:
    - docker-compose
    - elastic
    - zabbix-agent

- name: Настройка zabbix
  hosts: zabbix
  become: true

  roles:
    - zabbix-server
    - zabbix-agent